In [10]:
import numpy as np
lis2=[1,2,3,'4',5]
lis=[1,2,3,4,5]
arr=np.array(lis)
arr2=np.array(lis2)
print(arr)
print(arr2)
print(type(arr))

[1 2 3 4 5]
['1' '2' '3' '4' '5']
<class 'numpy.ndarray'>


In [12]:
arr3=np.array([[1,2,3,4],[5,6,7,8]])
print(arr3)

[[1 2 3 4]
 [5 6 7 8]]


In [26]:
arr4=np.arange(1,7)
print(arr4)
print(arr4.reshape(2,3))
arr5=np.zeros(5)
arr6=np.ones((3,3))
print(arr5)
print(arr6)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [34]:
lis=[1,2,3,4,5,6]
arr=np.array(lis)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)

1
(6,)
6
int64
8


In [39]:
arr=np.array([[1,2,3,4],[5,6,7,8],[3,4,5,6]])
print(arr)
print(arr[1,2])
print(arr[1,:])

[[1 2 3 4]
 [5 6 7 8]
 [3 4 5 6]]
7
[5 6 7 8]


In [42]:
arr=np.array([1,2,3,4,5])
print(arr[1:3])

[2 3]


In [53]:
arr=np.array([[10,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print(arr+arr2)
print(arr*arr2)
print(arr@arr2)
print(arr//arr2)
print(arr**arr2)
print(arr%arr2)
arr.transpose()

[[15  8]
 [10 12]]
[[50 12]
 [21 32]]
[[64 76]
 [43 50]]
[[2 0]
 [0 0]]
[[100000     64]
 [  2187  65536]]
[[0 2]
 [3 4]]


array([[10,  3],
       [ 2,  4]])

In [69]:
x=np.array([[12,11,15],[21,25,50],[18,27,16]])
y=np.sort(x,axis=1) #row wise sorting
k=np.sort(x,axis=0) #column wise sorting
z=np.argsort(x,axis=1) #retreive indices in sorted manner relative to original matrix
print(z)
print(y)

[[1 0 2]
 [0 1 2]
 [2 0 1]]
[[11 12 15]
 [21 25 50]
 [16 18 27]]


In [81]:
x=np.array([5,3,8,1])
y=np.sort(x)[::-1] #For sorting in descending order
z=np.argsort(x)
x.sort() #For sorting x array in place
print(y)
print(z)

[8 5 3 1]
[3 1 0 2]


In [89]:
x=np.array([1,2,3,4,5])
print(np.max(x))
print(np.min(x))
print(np.sum(x))
print(np.mean(x))
print(np.median(x))
y=np.std(x)
print(f"{y:.2f}")
print(np.var(x))
print(np.prod(x))

5
1
15
3.0
3.0
1.41
2.0
120
