<a href="https://colab.research.google.com/github/Uday00776/DataStorage/blob/main/chapter_appendix-tools-for-deep-learning/jupyter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
lis2=[1,2,3,'4',5]
lis=[1,2,3,4,5]
arr=np.array(lis)
arr2=np.array(lis2)
print(arr)
print(arr2)
print(type(arr))


[1 2 3 4 5]
['1' '2' '3' '4' '5']
<class 'numpy.ndarray'>


In [12]:
arr3=np.array([[1,2,3,4],[5,6,7,8]])
print(arr3)

[[1 2 3 4]
 [5 6 7 8]]


In [26]:
arr4=np.arange(1,7)
print(arr4)
print(arr4.reshape(2,3))
arr5=np.zeros(5)
arr6=np.ones((3,3))
print(arr5)
print(arr6)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [34]:
lis=[1,2,3,4,5,6]
arr=np.array(lis)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)

1
(6,)
6
int64
8
